import {
  DiGithubBadge,
  DiStackoverflow,
  DiNetmagazine,
  DiGit,
  DiOpensource,
  DiReact,
  DiMongodb,
  DiGulp,
  DiJavascript1,
  DiNpm,
  DiApple,
  DiWindows,
  DiLinux,
  DiUbuntu,
  DiPython,
  DiNginx,
  DiDocker,
  DiVisualstudio,
  DiJqueryLogo,
  DiGo,
  DiNodejsSmall,
} from "react-icons/di";

import { FaLinkedinIn, FaVuejs, FaEnvelope, FaYarn, FaJenkins } from "react-icons/fa";

export default {
  descriptionWords: [
    { heading: "", message: "I am a developer." },
    { heading: "", message: "My roots are in Systems Administration." },
    { heading: "From ", message: "Citrix.." },
    { heading: "To ", message: "Windows Server '03-'19..." },
    { heading: "To ", message: "Exchange '07-'19..." },
    { heading: "To ", message: "NAS/SAN..." },
    { heading: "To ", message: "VMware ESX(i)..." },
    { heading: "To ", message: "HP/Cisco Blades..." },
    { heading: "To ", message: "some Cisco networking..." },
    { heading: "I ", message: "have a wide variety of experience." },
    { heading: "With ", message: "over a decade of technical experience." },
    { heading: "I ", message: "am hungry for knowledge." },
    { heading: "I ", message: "enjoy back-end development." },
    { heading: "I ", message: "enjoy front-end development." },
    { heading: "I ", message: "am a tinkerer." },
    { heading: "I ", message: "am a lover of technology." },
    { heading: "I ", message: "want to understand how things work..." },
    { heading: "....", message: "and how to improve them." },
    { heading: "I ", message: "am a jack of all trades." },
    { heading: "I ", message: "have excellent troubleshooting skills." },
    { heading: "I ", message: "enjoy uptime." },
    { heading: "I ", message: "enjoy sports." },
    { heading: "...", message: "particularly, soccer. :)" },
    { heading: "I ", message: "have a Boston Terrier." },
  ],
  iconLinks: [
    {
      url: "https://github.com/oze4",
      icon: DiGithubBadge,
      tooltip: 'GitHub'
    },
    {
      url: "https://stackoverflow.com/users/10431732/matt-oestreich?tab=profile",
      icon: DiStackoverflow,
      tooltip: 'Stack Overflow',
    },
    {
      url: "https://www.linkedin.com/in/matt-oestreich-99251862/",
      icon: FaLinkedinIn,
      tooltip: 'LinkedIn',
    },
    {
      url: "",
      icon: FaEnvelope,
      tooltip: 'Reveal email address',
    },
  ],
  iconSkills: [
    { icon: DiGit, title: "Git", skill: 83 },
    { icon: DiOpensource, title: "Open Source Software", skill: 99 },
    { icon: DiNetmagazine, title: ".net", skill: 77 },
    { icon: DiPython, title: "Python", skill: 71 },
    { icon: DiVisualstudio, title: "Visual Studio", skill: 79 },
    { icon: DiJavascript1, title: "JavaScript", skill: 88 },
    { icon: DiJqueryLogo, title: "jQuery", skill: 86 },
    { icon: DiReact, title: "React.js", skill: 84 },
    { icon: FaVuejs, title: "Vue.js", skill: 80 },
    { icon: DiNodejsSmall, title: "Node", skill: 82 },
    { icon: DiGo, title: "Go", skill: 33 },
    { icon: DiMongodb, title: "MongoDB", skill: 77 },
    { icon: DiGulp, title: "Gulp", skill: 27 },
    { icon: DiNpm, title: "NPM", skill: 85 },
    { icon: FaYarn, title: "Yarn", skill: 85 },
    { icon: DiDocker, title: "Docker", skill: 66 },
    { icon: FaJenkins, title: "Jenkins", skill: 49 },
    { icon: DiNginx, title: "NGINX", skill: 44 },
    { icon: DiApple, title: "Apple", skill: 80 },
    { icon: DiWindows, title: "Microsoft", skill: 96 },
    { icon: DiLinux, title: "Linux", skill: 77 },
    { icon: DiUbuntu, title: "Ubuntu", skill: 77 },
  ],
};
